2021-04-15 17:22:12,374 INFO    MainThread:55049 [wandb_setup.py:_flush():69] setting env: {}
2021-04-15 17:22:12,377 INFO    MainThread:55049 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-15 17:22:12,377 INFO    MainThread:55049 [wandb_init.py:_log_setup():336] Logging user logs to /n/holyscratch01/Academic-cluster/Spring_2021/g_84102/SCRATCH/ImageNet/wandb/run-20210415_172212-34jhbujt/logs/debug.log
2021-04-15 17:22:12,377 INFO    MainThread:55049 [wandb_init.py:_log_setup():337] Logging internal logs to /n/holyscratch01/Academic-cluster/Spring_2021/g_84102/SCRATCH/ImageNet/wandb/run-20210415_172212-34jhbujt/logs/debug-internal.log
2021-04-15 17:22:12,378 INFO    MainThread:55049 [wandb_init.py:init():369] calling init triggers
2021-04-15 17:22:12,378 INFO    MainThread:55049 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-15 17:22:12,378 INFO    MainThread:55049 [wandb_init.py:init():418] starting backend
2021-04-15 17:22:12,378 INFO    MainThread:55049 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-15 17:22:12,432 INFO    MainThread:55049 [backend.py:ensure_launched():123] starting backend process...
2021-04-15 17:22:12,472 INFO    MainThread:55049 [backend.py:ensure_launched():127] started backend process with pid: 55412
2021-04-15 17:22:12,477 INFO    MainThread:55049 [wandb_init.py:init():423] backend started and connected
2021-04-15 17:22:12,482 INFO    MainThread:55049 [wandb_init.py:init():465] updated telemetry
2021-04-15 17:22:12,483 INFO    MainThread:55049 [wandb_init.py:init():484] communicating current version
2021-04-15 17:22:15,900 INFO    MainThread:55049 [wandb_init.py:init():489] got version response 
2021-04-15 17:22:15,901 INFO    MainThread:55049 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-15 17:22:16,115 INFO    MainThread:55049 [wandb_init.py:init():522] starting run threads in backend
2021-04-15 17:22:21,131 INFO    MainThread:55049 [wandb_run.py:_console_start():1524] atexit reg
2021-04-15 17:22:21,136 INFO    MainThread:55049 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-15 17:22:21,137 INFO    MainThread:55049 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-15 17:22:21,140 INFO    MainThread:55049 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-15 17:22:21,140 INFO    MainThread:55049 [wandb_init.py:init():546] run started, returning control to user process
2021-04-15 17:30:51,547 INFO    MainThread:55049 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 255
2021-04-15 17:30:51,550 INFO    MainThread:55049 [wandb_run.py:_restore():1466] restore
2021-04-15 17:30:53,562 INFO    MainThread:55049 [wandb_run.py:_restore():1466] restore
2021-04-15 17:30:59,481 ERROR   MainThread:55049 [wandb_run.py:_atexit_cleanup():1512] Problem finishing run
Traceback (most recent call last):
  File "/n/academic_homes/g_84102/u_358858_g_84102/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1502, in _atexit_cleanup
    self._on_finish()
  File "/n/academic_homes/g_84102/u_358858_g_84102/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1659, in _on_finish
    self._backend.interface.publish_telemetry(self._telemetry_obj)
  File "/n/academic_homes/g_84102/u_358858_g_84102/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 231, in publish_telemetry
    self._publish(rec)
  File "/n/academic_homes/g_84102/u_358858_g_84102/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 524, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
